name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: ./gradlew build

    - uses: ashley-taylor/junit-report-annotations-action@1.2
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/TEST-*.xml"
