name: Java CI with Gradle

on:
  push:
  pull_request:
    branches:
      - master
      - main/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # --continue is used to get all JUnit reports despite failures
    - name: Build
      run: ./gradlew build --continue

    - uses: ashley-taylor/junit-report-annotations-action@1.2
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/TEST-*.xml"
