name: Java CI with Gradle

on:
  push:
  pull_request:
    branches:
      - master
      - main/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./gradlew build

    - uses: turpif/junit-report-annotations-action@gradle
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
